import type { Metadata } from "next";
import "./globals.css";
import LeftPanel from "@/components/LeftPanel";
import { getChats } from "@/lib/chats/data";
import { SidebarProvider } from "@/lib/context/SidebarContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const chats = await getChats();
  return (
    <html lang="en">
      <body className="sans-serif antialiased">
        <SidebarProvider initialChats={chats} initialSidebarHidden={false}>
          <div className="flex flex-row">
            <LeftPanel />
            {children}
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
