import type { Metadata } from "next";
import "./globals.css";
import LeftPanel from "@/components/LeftPanel";
import { getChats } from "@/lib/chats/data";
import { SidebarProvider } from "@/lib/context/SidebarContext";
import { chatModels } from "@/lib/models";
import { ModelProvider } from "@/lib/context/ModelContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const chats = await getChats();
  return (
    <html lang="en">
      <body className="sans-serif antialiased">
        <SidebarProvider initialChats={chats} initialSidebarHidden={true}>
          <ModelProvider initialModel={chatModels["gpt-4o"]}>
            <div className="flex flex-row">
              <LeftPanel />
              {children}
            </div>
          </ModelProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
